# Generated by Django 3.0.5 on 2020-05-12 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_formfield_formpage'),
        ('comment', '0002_commentpeoplerelationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='people',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='person_comment_relationship', to='base.People'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CommentPeopleRelationship',
        ),
    ]
