# Generated by Django 3.0.5 on 2020-05-12 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20200512_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='people',
            new_name='user',
        ),
    ]
