# Generated by Django 3.0.5 on 2020-05-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200512_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='subtitle',
            new_name='category',
        ),
    ]
