# Generated by Django 3.0.5 on 2020-05-14 19:30

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200514_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.BlogCategory'),
        ),
        migrations.DeleteModel(
            name='BlogCategoryBlogPage',
        ),
    ]
