export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAIL = "FETCH_POSTS_FAIL";
export const LOADING_FETCH_POSTS = "LOADING_FETCH_POSTS";

export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_TAGS_SUCCESS = "FETCH_TAGS_SUCCESS";

export const HERO_ANIMATION_DONE = "HERO_ANIMATION_DONE";
